function X_new = low_rank_frobenius_step_test(X, E, r,alpha)
    n = size(X,2);
    E = E - trace(X' * E) * X;
    [U, S, Vh] = svd(X, 'econ');
    s = diag(S);
    X_proj = U(:, 1:r) * diag(s(1:r)) * Vh(:, 1:r)';
    X = X_proj / norm(X_proj, 'fro');
    [U1, s1, Vh1] = svd(X, 'econ');
    H = U1(:,1:r) * diag(s1(1:r));
    H_norm = norm(H,'fro');
    H = H/H_norm;
    V = Vh1(:, 1:r);
    V = V*H_norm;
    G = eye(n) - V * V';
    M_H = 20 * eye(r) + H' * H;
    Vp = G * E' * H / M_H;
    mid = E * V;
    K = mid - trace(H' * mid) * H;
    V_tl = (V - alpha*Vp) / sqrtm(eye(r) + (alpha*Vp)'*(alpha*Vp));
    X_retracted = ((H - alpha*K) / norm(H - alpha*K, 'fro')) * V_tl';
    %G_retracted = eye(size(G)) - V_tl * V_tl';
    X_new = X_retracted;
    %G_new = G_retracted;
end
